#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    A= int(input().strip())
    if A % 2 != 0:
        print("Weird")
    elif A % 2 == 0 and A in range(2,5):
        print("Not Weird")
    elif A % 2 == 0 and A in range(6,21):
        print("Weird")
    else:
        print("Not Weird")    
